[package]
name = "parcom"
edition.workspace = true
version.workspace = true

[dependencies]
parcom-core = { workspace = true }
parcom-metrics = { workspace = true }
parcom-parsers = { workspace = true }
parcom-util = { workspace = true }
